name: travel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
     

  # HTTP & networking
  http: ^1.2.1

  # QR & image
  mobile_scanner: ^5.0.0
  google_mlkit_barcode_scanning: ^0.10.0
  image_picker: ^1.1.2

  # Speech recognition
  speech_to_text: ^6.6.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  url_launcher: ^6.0.0

  # Video
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos//video1.mp4
    - assets/videos/video2.mp4
    - assets/videos/video3.mp4
    - assets/videos/video4.mp4
    - assets/videos/video5.mp4
    - assets/videos/video6.mp4
    - assets/images/kathakali.png
    - assets/images/munnar.jpg
    - assets/images/kochi.jpg
    - assets/images/alleppey.jpg
    - assets/images/wayanad.jpg
    - assets/images/profile.jpg
    - assets/images/boat.png  # ← add this